use crate::header::location::subregion::Subregion;

#[derive(thiserror::Error, Debug)]
pub enum CountryError {
    #[error("Nonexistent Country")]
    NonexistentCountry,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Country {
    Japan,
    Antarctica,
    CaribbeanNetherlands,
    FalklandIslands,
    Scotland,
    Wales,
    SintMaarten,
    Anguilla,
    AntiguaAndBarbuda,
    Argentina,
    Aruba,
    Bahamas,
    Barbados,
    Belize,
    Bolivia,
    Brazil,
    BritishVirginIslands,
    Canada,
    CaymanIslands,
    Chile,
    Colombia,
    CostaRica,
    Dominica,
    DominicanRepublic,
    Ecuador,
    ElSalvador,
    FrenchGuiana,
    Grenada,
    Guadeloupe,
    Guatemala,
    Guyana,
    Haiti,
    Honduras,
    Jamaica,
    Martinique,
    Mexico,
    Montserrat,
    Curacao,
    Nicaragua,
    Panama,
    Paraguay,
    Peru,
    StKittsAndNevis,
    StLucia,
    StVincentAndTheGrenadines,
    Suriname,
    TrinidadAndTobago,
    TurksAndCaicosIslands,
    UnitedStates,
    Uruguay,
    USVirginIslands,
    Venezuela,
    Armenia,
    Belarus,
    NetherlandsAntilles,
    Georgia,
    Kosovo,
    Abkhazia,
    Catalonia,
    England,
    SouthOssetia,
    Bougainville,
    Aland,
    FaroeIslands,
    Albania,
    Australia,
    Austria,
    Belgium,
    BosniaHerzegovina,
    Botswana,
    Bulgaria,
    Croatia,
    Cyprus,
    Czechia,
    Denmark,
    Estonia,
    Finland,
    France,
    Germany,
    Greece,
    Hungary,
    Iceland,
    Ireland,
    Italy,
    Latvia,
    Lesotho,
    Liechtenstein,
    Lithuania,
    Luxembourg,
    NorthMacedonia,
    Malta,
    Montenegro,
    Mozambique,
    Namibia,
    Netherlands,
    NewZealand,
    Norway,
    Poland,
    Portugal,
    Romania,
    Russia,
    Serbia,
    Slovakia,
    Slovenia,
    SouthAfrica,
    Spain,
    Eswatini,
    Sweden,
    Switzerland,
    Turkey,
    UnitedKingdom,
    Zambia,
    Zimbabwe,
    Azerbaijan,
    Mauritania,
    Mali,
    Niger,
    Chad,
    Sudan,
    Eritrea,
    Djibouti,
    Somalia,
    Andorra,
    Gibraltar,
    Guernsey,
    IsleOfMan,
    Jersey,
    Monaco,
    Taiwan,
    Cambodia,
    Laos,
    Mongolia,
    Myanmar,
    Nepal,
    Vietnam,
    NorthKorea,
    SouthKorea,
    Bangladesh,
    Bhutan,
    Brunei,
    Maldives,
    SriLanka,
    TimorLeste,
    BritishIndianOceanTerritory,
    HongKong,
    Macao,
    CookIslands,
    Niue,
    NorfolkIsland,
    NorthernMarianaIslands,
    AmericanSamoa,
    Guam,
    Indonesia,
    Singapore,
    Thailand,
    Philippines,
    Malaysia,
    SaintBarthelemy,
    SaintMartin,
    SaintPierreAndMiquelon,
    China,
    Afghanistan,
    Kazakhstan,
    Kyrgyzstan,
    Pakistan,
    Tajikistan,
    Turkmenistan,
    Uzbekistan,
    UnitedArabEmirates,
    India,
    Egypt,
    Oman,
    Qatar,
    Kuwait,
    SaudiArabia,
    Syria,
    Bahrain,
    Jordan,
    Iran,
    Iraq,
    Israel,
    Lebanon,
    Yemen,
    SanMarino,
    VaticanCity,
    Bermuda,
    FrenchPolynesia,
    Reunion,
    Mayotte,
    NewCaledonia,
    WallisAndFutuna,
    Nigeria,
    Angola,
    Ghana,
    Togo,
    Benin,
    BurkinaFaso,
    IvoryCoast,
    Liberia,
    SierraLeone,
    Guinea,
    GuineaBissau,
    Senegal,
    TheGambia,
    CapeVerde,
    SaintHelenaAscensionAndTristandaCunha,
    Moldova,
    Ukraine,
    Cameroon,
    CentralAfricanRepublic,
    DemocraticRepublicOfTheCongo,
    RepublicOfTheCongo,
    EquatorialGuinea,
    Gabon,
    SaoTomeAndPríncipe,
    Algeria,
    Ethiopia,
    Libya,
    Morocco,
    SouthSudan,
    Tunisia,
    SahrawiArabDemocraticRepublic,
    Cuba,
    Burundi,
    Comoros,
    Kenya,
    Madagascar,
    Malawi,
    Mauritius,
    Rwanda,
    Seychelles,
    Tanzania,
    Uganda,
    FrenchSouthernAndAntarcticLands,
    PitcairnIslands,
    BritishAntarcticTerritory,
    SouthGeorgiaAndTheSouthSandwichIslands,
    FederatedStatesOfMicronesia,
    Fiji,
    Kiribati,
    MarshallIslands,
    Nauru,
    Palau,
    PapuaNewGuinea,
    Samoa,
    SolomonIslands,
    Tokelau,
    Tonga,
    Tuvalu,
    Vanuatu,
    ChristmasIsland,
    CocosKeelingIslands,
    PuertoRico,
    Greenland,
    Artsakh,
    NorthernCyprus,
    Transnistria,
    Palestine,
    Somaliland,
    Bonaire,
    Saba,
    SintEustatius,
    NotSet,
}

impl std::fmt::Display for Country {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Country::Japan => write!(f, "Japan"),
            Country::Antarctica => write!(f, "Antarctica"),
            Country::Bonaire => write!(f, "Bonaire"),
            Country::FalklandIslands => write!(f, "Falkland Islands"),
            Country::Saba => write!(f, "Saba"),
            Country::SintEustatius => write!(f, "Sint Eustatius"),
            Country::SintMaarten => write!(f, "Sint Maarten"),
            Country::Anguilla => write!(f, "Anguilla"),
            Country::AntiguaAndBarbuda => write!(f, "Antigua and Barbuda"),
            Country::Argentina => write!(f, "Argentina"),
            Country::Aruba => write!(f, "Aruba"),
            Country::Bahamas => write!(f, "Bahamas"),
            Country::Barbados => write!(f, "Barbados"),
            Country::Belize => write!(f, "Belize"),
            Country::Bolivia => write!(f, "Bolivia"),
            Country::Brazil => write!(f, "Brazil"),
            Country::BritishVirginIslands => write!(f, "British Virgin Islands"),
            Country::Canada => write!(f, "Canada"),
            Country::CaymanIslands => write!(f, "Cayman Islands"),
            Country::Chile => write!(f, "Chile"),
            Country::Colombia => write!(f, "Colombia"),
            Country::CostaRica => write!(f, "Costa Rica"),
            Country::Dominica => write!(f, "Dominica"),
            Country::DominicanRepublic => write!(f, "Dominican Republic"),
            Country::Ecuador => write!(f, "Ecuador"),
            Country::ElSalvador => write!(f, "El Salvador"),
            Country::FrenchGuiana => write!(f, "French Guiana"),
            Country::Grenada => write!(f, "Grenada"),
            Country::Guadeloupe => write!(f, "Guadeloupe"),
            Country::Guatemala => write!(f, "Guatemala"),
            Country::Guyana => write!(f, "Guyana"),
            Country::Haiti => write!(f, "Haiti"),
            Country::Honduras => write!(f, "Honduras"),
            Country::Jamaica => write!(f, "Jamaica"),
            Country::Martinique => write!(f, "Martinique"),
            Country::Mexico => write!(f, "Mexico"),
            Country::Montserrat => write!(f, "Montserrat"),
            Country::Curacao => write!(f, "Curaçao"),
            Country::Nicaragua => write!(f, "Nicaragua"),
            Country::Panama => write!(f, "Panama"),
            Country::Paraguay => write!(f, "Paraguay"),
            Country::Peru => write!(f, "Peru"),
            Country::StKittsAndNevis => write!(f, "St. Kitts and Nevis"),
            Country::StLucia => write!(f, "St. Lucia"),
            Country::StVincentAndTheGrenadines => write!(f, "St. Vincent and the Grenadines"),
            Country::Suriname => write!(f, "Suriname"),
            Country::TrinidadAndTobago => write!(f, "Trinidad and Tobago"),
            Country::TurksAndCaicosIslands => write!(f, "Turks and Caicos Islands"),
            Country::UnitedStates => write!(f, "United States"),
            Country::Uruguay => write!(f, "Uruguay"),
            Country::USVirginIslands => write!(f, "US Virgin Islands"),
            Country::Venezuela => write!(f, "Venezuela"),
            Country::Armenia => write!(f, "Armenia"),
            Country::Belarus => write!(f, "Belarus"),
            Country::Georgia => write!(f, "Georgia"),
            Country::Kosovo => write!(f, "Kosovo"),
            Country::Abkhazia => write!(f, "Abkhazia"),
            Country::Artsakh => write!(f, "Artsakh"),
            Country::NorthernCyprus => write!(f, "Northern Cyprus"),
            Country::SouthOssetia => write!(f, "South Ossetia"),
            Country::Transnistria => write!(f, "Transnistria"),
            Country::Aland => write!(f, "Åland"),
            Country::FaroeIslands => write!(f, "Faroe Islands"),
            Country::Albania => write!(f, "Albania"),
            Country::Australia => write!(f, "Australia"),
            Country::Austria => write!(f, "Austria"),
            Country::Belgium => write!(f, "Belgium"),
            Country::BosniaHerzegovina => write!(f, "Bosnia & Herzegovina"),
            Country::Botswana => write!(f, "Botswana"),
            Country::Bulgaria => write!(f, "Bulgaria"),
            Country::Croatia => write!(f, "Croatia"),
            Country::Cyprus => write!(f, "Cyprus"),
            Country::Czechia => write!(f, "Czechia"),
            Country::Denmark => write!(f, "Denmark"),
            Country::Estonia => write!(f, "Estonia"),
            Country::Finland => write!(f, "Finland"),
            Country::France => write!(f, "France"),
            Country::Germany => write!(f, "Germany"),
            Country::Greece => write!(f, "Greece"),
            Country::Hungary => write!(f, "Hungary"),
            Country::Iceland => write!(f, "Iceland"),
            Country::Ireland => write!(f, "Ireland"),
            Country::Italy => write!(f, "Italy"),
            Country::Latvia => write!(f, "Latvia"),
            Country::Lesotho => write!(f, "Lesotho"),
            Country::Liechtenstein => write!(f, "Liechtenstein"),
            Country::Lithuania => write!(f, "Lithuania"),
            Country::Luxembourg => write!(f, "Luxembourg"),
            Country::NorthMacedonia => write!(f, "North Macedonia"),
            Country::Malta => write!(f, "Malta"),
            Country::Montenegro => write!(f, "Montenegro"),
            Country::Mozambique => write!(f, "Mozambique"),
            Country::Namibia => write!(f, "Namibia"),
            Country::Netherlands => write!(f, "Netherlands"),
            Country::NewZealand => write!(f, "New Zealand"),
            Country::Norway => write!(f, "Norway"),
            Country::Poland => write!(f, "Poland"),
            Country::Portugal => write!(f, "Portugal"),
            Country::Romania => write!(f, "Romania"),
            Country::Russia => write!(f, "Russia"),
            Country::Serbia => write!(f, "Serbia"),
            Country::Slovakia => write!(f, "Slovakia"),
            Country::Slovenia => write!(f, "Slovenia"),
            Country::SouthAfrica => write!(f, "South Africa"),
            Country::Spain => write!(f, "Spain"),
            Country::Eswatini => write!(f, "Eswatini"),
            Country::Sweden => write!(f, "Sweden"),
            Country::Switzerland => write!(f, "Switzerland"),
            Country::Turkey => write!(f, "Turkey"),
            Country::UnitedKingdom => write!(f, "United Kingdom"),
            Country::Zambia => write!(f, "Zambia"),
            Country::Zimbabwe => write!(f, "Zimbabwe"),
            Country::Azerbaijan => write!(f, "Azerbaijan"),
            Country::Mauritania => write!(f, "Mauritania"),
            Country::Mali => write!(f, "Mali"),
            Country::Niger => write!(f, "Niger"),
            Country::Chad => write!(f, "Chad"),
            Country::Sudan => write!(f, "Sudan"),
            Country::Eritrea => write!(f, "Eritrea"),
            Country::Djibouti => write!(f, "Djibouti"),
            Country::Somalia => write!(f, "Somalia"),
            Country::Andorra => write!(f, "Andorra"),
            Country::Gibraltar => write!(f, "Gibraltar"),
            Country::Guernsey => write!(f, "Guernsey"),
            Country::IsleOfMan => write!(f, "Isle of Man"),
            Country::Jersey => write!(f, "Jersey"),
            Country::Monaco => write!(f, "Monaco"),
            Country::Taiwan => write!(f, "Taiwan"),
            Country::Cambodia => write!(f, "Cambodia"),
            Country::Laos => write!(f, "Laos"),
            Country::Mongolia => write!(f, "Mongolia"),
            Country::Myanmar => write!(f, "Myanmar"),
            Country::Nepal => write!(f, "Nepal"),
            Country::Vietnam => write!(f, "Vietnam"),
            Country::NorthKorea => write!(f, "North Korea"),
            Country::SouthKorea => write!(f, "South Korea"),
            Country::Bangladesh => write!(f, "Bangladesh"),
            Country::Bhutan => write!(f, "Bhutan"),
            Country::Brunei => write!(f, "Brunei"),
            Country::Maldives => write!(f, "Maldives"),
            Country::SriLanka => write!(f, "Sri Lanka"),
            Country::TimorLeste => write!(f, "Timor-Leste"),
            Country::BritishIndianOceanTerritory => write!(f, "British Indian Ocean Territory"),
            Country::HongKong => write!(f, "Hong Kong"),
            Country::Macao => write!(f, "Macao"),
            Country::CookIslands => write!(f, "Cook Islands"),
            Country::Niue => write!(f, "Niue"),
            Country::NorfolkIsland => write!(f, "Norfolk Island"),
            Country::NorthernMarianaIslands => write!(f, "Northern Mariana Islands"),
            Country::AmericanSamoa => write!(f, "American Samoa"),
            Country::Guam => write!(f, "Guam"),
            Country::Indonesia => write!(f, "Indonesia"),
            Country::Singapore => write!(f, "Singapore"),
            Country::Thailand => write!(f, "Thailand"),
            Country::Philippines => write!(f, "Philippines"),
            Country::Malaysia => write!(f, "Malaysia"),
            Country::SaintBarthelemy => write!(f, "Saint Barthélemy"),
            Country::SaintMartin => write!(f, "Saint Martin"),
            Country::SaintPierreAndMiquelon => write!(f, "Saint Pierre and Miquelon"),
            Country::China => write!(f, "China"),
            Country::Afghanistan => write!(f, "Afghanistan"),
            Country::Kazakhstan => write!(f, "Kazakhstan"),
            Country::Kyrgyzstan => write!(f, "Kyrgyzstan"),
            Country::Pakistan => write!(f, "Pakistan"),
            Country::Tajikistan => write!(f, "Tajikistan"),
            Country::Turkmenistan => write!(f, "Turkmenistan"),
            Country::Uzbekistan => write!(f, "Uzbekistan"),
            Country::UnitedArabEmirates => write!(f, "U.A.E"),
            Country::India => write!(f, "India"),
            Country::Egypt => write!(f, "Egypt"),
            Country::Oman => write!(f, "Oman"),
            Country::Qatar => write!(f, "Qatar"),
            Country::Kuwait => write!(f, "Kuwait"),
            Country::SaudiArabia => write!(f, "Saudi Arabia"),
            Country::Syria => write!(f, "Syria"),
            Country::Bahrain => write!(f, "Bahrain"),
            Country::Jordan => write!(f, "Jordan"),
            Country::Iran => write!(f, "Iran"),
            Country::Iraq => write!(f, "Iraq"),
            Country::Israel => write!(f, "Israel"),
            Country::Lebanon => write!(f, "Lebanon"),
            Country::Palestine => write!(f, "Palestine"),
            Country::Yemen => write!(f, "Yemen"),
            Country::SanMarino => write!(f, "San Marino"),
            Country::VaticanCity => write!(f, "Vatican City"),
            Country::Bermuda => write!(f, "Bermuda"),
            Country::FrenchPolynesia => write!(f, "French Polynesia"),
            Country::Reunion => write!(f, "Réunion"),
            Country::Mayotte => write!(f, "Mayotte"),
            Country::NewCaledonia => write!(f, "New Caledonia"),
            Country::WallisAndFutuna => write!(f, "Wallis and Futuna"),
            Country::Nigeria => write!(f, "Nigeria"),
            Country::Angola => write!(f, "Angola"),
            Country::Ghana => write!(f, "Ghana"),
            Country::Togo => write!(f, "Togo"),
            Country::Benin => write!(f, "Benin"),
            Country::BurkinaFaso => write!(f, "Burkina Faso"),
            Country::IvoryCoast => write!(f, "Côte d'Ivoire"),
            Country::Liberia => write!(f, "Liberia"),
            Country::SierraLeone => write!(f, "Sierra Leone"),
            Country::Guinea => write!(f, "Guinea"),
            Country::GuineaBissau => write!(f, "Guinea-Bissau"),
            Country::Senegal => write!(f, "Senegal"),
            Country::TheGambia => write!(f, "The Gambia"),
            Country::CapeVerde => write!(f, "Cape Verde"),
            Country::SaintHelenaAscensionAndTristandaCunha => {
                write!(f, "Saint Helena, Ascension and Tristan da Cunha")
            }
            Country::Moldova => write!(f, "Moldova"),
            Country::Ukraine => write!(f, "Ukraine"),
            Country::Cameroon => write!(f, "Cameroon"),
            Country::CentralAfricanRepublic => write!(f, "Central African Republic"),
            Country::DemocraticRepublicOfTheCongo => write!(f, "Democratic Republic of the Congo"),
            Country::RepublicOfTheCongo => write!(f, "Republic of the Congo"),
            Country::EquatorialGuinea => write!(f, "Equatorial Guinea"),
            Country::Gabon => write!(f, "Gabon"),
            Country::SaoTomeAndPríncipe => write!(f, "São Tomé and Príncipe"),
            Country::Algeria => write!(f, "Algeria"),
            Country::Ethiopia => write!(f, "Ethiopia"),
            Country::Libya => write!(f, "Libya"),
            Country::Morocco => write!(f, "Morocco"),
            Country::SouthSudan => write!(f, "South Sudan"),
            Country::Tunisia => write!(f, "Tunisia"),
            Country::SahrawiArabDemocraticRepublic => write!(f, "Sahrawi Arab Democratic Republic"),
            Country::Somaliland => write!(f, "Somaliland"),
            Country::Burundi => write!(f, "Burundi"),
            Country::Comoros => write!(f, "Comoros"),
            Country::Kenya => write!(f, "Kenya"),
            Country::Madagascar => write!(f, "Madagascar"),
            Country::Malawi => write!(f, "Malawi"),
            Country::Mauritius => write!(f, "Mauritius"),
            Country::Rwanda => write!(f, "Rwanda"),
            Country::Seychelles => write!(f, "Seychelles"),
            Country::Tanzania => write!(f, "Tanzania"),
            Country::Uganda => write!(f, "Uganda"),
            Country::FrenchSouthernAndAntarcticLands => {
                write!(f, "French Southern and Antarctic Lands")
            }
            Country::PitcairnIslands => write!(f, "Pitcairn Islands"),
            Country::BritishAntarcticTerritory => write!(f, "British Antarctic Territory"),
            Country::SouthGeorgiaAndTheSouthSandwichIslands => {
                write!(f, "South Georgia and the South Sandwich Islands")
            }
            Country::FederatedStatesOfMicronesia => write!(f, "Federated States of Micronesia"),
            Country::Fiji => write!(f, "Fiji"),
            Country::Kiribati => write!(f, "Kiribati"),
            Country::MarshallIslands => write!(f, "Marshall Islands"),
            Country::Nauru => write!(f, "Nauru"),
            Country::Palau => write!(f, "Palau"),
            Country::PapuaNewGuinea => write!(f, "Papua New Guinea"),
            Country::Samoa => write!(f, "Samoa"),
            Country::SolomonIslands => write!(f, "Solomon Islands"),
            Country::Tokelau => write!(f, "Tokelau"),
            Country::Tonga => write!(f, "Tonga"),
            Country::Tuvalu => write!(f, "Tuvalu"),
            Country::Vanuatu => write!(f, "Vanuatu"),
            Country::ChristmasIsland => write!(f, "Christmas Island"),
            Country::CocosKeelingIslands => write!(f, "Cocos (Keeling) Islands"),
            Country::PuertoRico => write!(f, "Puerto Rico"),
            Country::Greenland => write!(f, "Greenland"),
            Country::CaribbeanNetherlands => write!(f, "Carabbean Netherlands"),
            Country::Scotland => write!(f, "Scotland"),
            Country::Wales => write!(f, "Wales"),
            Country::Catalonia => write!(f, "Catalonia"),
            Country::England => write!(f, "England"),
            Country::Cuba => write!(f, "Cuba"),
            Country::Bougainville => write!(f, "Bougainville"),
            Country::NetherlandsAntilles => write!(f, "Netherlands Antilles"),
            Country::NotSet => write!(f, "Not Set"),
        }
    }
}
